apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: bob-csr
spec:
  groups:
    - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2FUQ0NBVkVDQVFBd0pERU1NQW9HQTFVRUF3d0RRbTlpTVJRd0VnWURWUVFLREF0RmJtZHBibVZsY21sdQpaekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMVWtZOWVQK01MeklCcU9nTFlwCmJqN05UMktkZ29PdWo3Q211cmtHbnErcDY0YmNJR296Vmxsb0xuQ2xnYVBTYW92anhWLys4MUNsYjQ1czRtQXkKdCtQK3owTnFTVnBoaklyVFc3VXFsZHpNMjFkdVVaYTF3N0FjcTNSOTc5L29Xd3RTUkoySERCNXBtSno1ejlPVAp1ZDFOOTFYUU9Jcy9jdGE0T21QMXdKRS9tb25PekhZRklBT1BmVnF5c0FPNHEweGpPdmw0b3VXTHJKQmdCV21wCnBMZStGamFUZDNpWDN6WEJNbG9DZzR0UXR0Ni9jKytub0lsUWY1S09qdTRIOVJURnNIQkNoc0hSOE9yMnovUWgKQy9kM0lPSWY5Ky8zTlBhSVc0Rkd5MHZvaGZpVDcxcVM3V0RJMkhVRlM5NUc1SnYwZmppMk9GcWtVYitzNlZCVwpCZFVDQXdFQUFhQUFNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFrbnVEVTkvM3FUVmZrR3pIQVJTZUpKVFU3Cmc0N0NNUHpwdmozQnJZZklsZ3Z5cXpzVkJPYWE2UXIvMFR1VzBEaVYwYmtXaEhlOEVvb2YxRi9CYXhDanlZc1kKUytFMlovV2JSVFVCajJYM2puazBMSjFzUjJPb28rak1MS3d5QVVhRkJCZU5pN3JnWkgvU3RROHo1TzBVQjErLwpTUmVDRXduS3hRbjFRQVd0UVBGamplN2JLNVlOT1Y0aGlsMWJNOElWT0ozalJqUXAwL3hCeWZJaUVpZ25zMzVvClN3b05NaDJTUTB2cU9oWkNrVjRjelltL2NjQUozYW1wVXlETW02amdmclNONml3d3lCbU5vSFJyeTU1R0ZpQUkKbjJIbzJYTTBRU0NoeDc3NGNLUTBzWXZUTkp1N3hjTEFMaGwyVmg3ZEFORHgvdFFEWDE1YnUwcUxRTlJpCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 86400
  usages:
    - client auth
