apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-secrets
  namespace: dev
spec:
  selector:
    matchLabels:
      app: sealed-secrets
  template:
    metadata:
      labels:
        app: sealed-secrets
    spec:
      containers:
        - name: sealed-secrets
          image: antonputra/043:v0.1.5
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: credentials-volume
              mountPath: "/etc/credentials"
              readOnly: true
      volumes:
        - name: credentials-volume
          secret:
            secretName: credentials
            # you can decide which key to mount as file
            items:
              - key: username
                path: username
              - key: password
                path: password
