---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: dev
spec:
  encryptedData:
    password: AgBxm9gQNnGesxMG17X4O/hy+yhmpx692LJBCI2u/dT9qLr3SqvuqoYmP0/EzxmEYKqKZGJJLL+L0nksIDM2od7EiWvgllvSQkjWcvpdP/8ZTk6I8LxfHqFK34cyu1a1gfUu5lXa6dwm/sLUJ9vKU9ZxOcQdyaju1QPMVaHTQHTBFpJOGS47Adf2JzqQMiwXE2kURrAVeCrPuYyvZaE6gZTLyfwQLWN4NnqZLq9laolZp1J7cSHMY4yHxjRuj/vSpbzfsDZsihQpLHtrfu9UQhN/HWGfdn0N7GzYNIcuXsloXkBQE5wjpSK53khzXsIrGBafk5I2sdEXO1mdiJpx13e52CWur+JIjNXBj9WLZOplR8Eza/1Mn4to1kKd+Bgy0uvhhZBnUXc5izaCS1eF9CK2RG8RawIskKBERGt0tp+P57ZKpIe2U74fRuULjbyUBnRJh45Cvjse4VcaryfSMpAgzPSbpBtA5al7Ii633vM2PDkPG1ORZuwLIuoFEbE6tZUaNnZUggMwVOmuyb5qDYx2QOpQeqCI5zvjNbMJ9kDy+u8lCIawy6SZnvdps8LEHV9GNmEZwTIokH/IHRP4FVG4mEvLFc2ShdjfQFk6KLl+HJRIu//0X/ZFsRrxwGBxilCy3dJXwhgLqs7uJQjGm8wagj1pVKa0azLXWl7EbiIZbc6YYcVHo2XZhgqIqUcx+nVeAdVvtOQdy5k=
    username: AgB24STfIxyP2rbfZyy+eEFnokYsXLHXoBXMPlZbNN7dqHaJJFl6PLtzfnCRennvNgr4vhha6LtDkM4RTK0oHbJAJn1I7I+vSppM9yjfNegYAMfgo6YWBn45X7QFAB21GGc/3x8TBgIENG9pyJdXFECtoI+vuuNkbx70AE/KxkWloiE6vRse8s2aT86z2Bz0kCpd0OFO6TQ8/cuwLoTJ0djk8lxiyFd9wHwKzthxYe8g0PsxTSHIcK2WzrNlQU4NIEi7vqEVqB4MRq6MjS0L1WB65JORVML1Jq15Q/jE7hVaLBCTW3Gxue7D3vdN3BXlYAa36EFI8WfzioS8FkbUHzsUuQCQ4Ccp5bDpQNoECWSj6XcqsE1H/EvnrVpwbS+oATKe6q/KeybPO+qgtLeZ+RWZZzosx74cW8HY6j65TkZMsZaOfXpw43Xl7H5wkcZ5Or6F+3VfJ8EGyID1ogAJcrY3LSPw4QGFSybZw91CyOrsjYnIL373KuOCnU/g2R9meh9yuHci9XoyMFojNgr0tUto1XnwDdEIBY8kxdVcnVHhaIVmuwXwHXNgzXnZra5Epmzu2MXrNwEZq00O3EOJT2oIlp0n7j0V2RS+oiFZg/adDxGM71y4aeBUAXQvTXa1yGc1S5n3tzawz/MdcVSSUdCpm+HHw18hLlmWwkB2PfxssMaHXr4LzMQQ9K/baHYMpVa2ZfEfdtE=
  template:
    metadata:
      creationTimestamp: null
      name: credentials
      namespace: dev
    type: Opaque
