apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook
webhooks:
  - name: webhook.webhook.svc.cluster.local
    admissionReviewVersions:
      - "v1"
    # It tells the Kubernetes API server that the webhook's operations are safe and idempotent
    sideEffects: "None"
    timeoutSeconds: 30
    objectSelector:
      matchLabels:
        webhook-enabled: "true"
    clientConfig:
      service:
        name: webhook
        namespace: webhook
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURuekNDQW9lZ0F3SUJBZ0lVU2Q2dmZMemFXWUxINlN0WU5Xc0V2VnlNTi9nd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1VqRUxNQWtHQTFVRUJoTUNRVlV4RURBT0JnTlZCQWdNQjBWNFlXMXdiR1V4RWpBUUJnTlZCQWNNQ1UxbApiR0p2ZFhKdVpURVFNQTRHQTFVRUNnd0hSWGhoYlhCc1pURUxNQWtHQTFVRUN3d0NRMEV3SGhjTk1qVXdOVEUyCk1ETXlPREExV2hjTk5EVXdOVEV4TURNeU9EQTFXakJTTVFzd0NRWURWUVFHRXdKQlZURVFNQTRHQTFVRUNBd0gKUlhoaGJYQnNaVEVTTUJBR0ExVUVCd3dKVFdWc1ltOTFjbTVsTVJBd0RnWURWUVFLREFkRmVHRnRjR3hsTVFzdwpDUVlEVlFRTERBSkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMUGt0RmxuCkt6QWVZanROcHNrNThRRUxJN2EwRExTT1RLUVd2Y050RGx1dUJvOHg4Y0JFWEdxSS9US1VXdzRyUCtidVMzN1gKeEYyaFY5UU1sZnd5S2NCd3RGMnkzVzY4OVk5VE1JSldCNVZvT0JUNndFUm5yNU8xcG9TdkxVSFd0WUoweStBVgpTaDhUZHROV1k2Qi9wS3ZyZXgvU3NaQ1RPeGY0UkJpUjhNVW9Rem1NQWhzSFlwMnV4TTVkUCt5cWxaYjMxZHFyCmFNbW5WM2hkeW9EOGpjZkRncHY2ZGdQL1N2eFBrWTgvR1UvRHB5VkV3SUt4VUxoSWlJVXBQdnBtUWFXVE1PdVEKcll2NnBHTGpuYnBwMEhMMUx5QzYzZUh0MjdETS9KNWNFZHVmaG1lVGduVVg1TVcxbTRKbmNFY3BvV1U5QUxiVwozazhsbG9ZN0NNeWN5RE1DQXdFQUFhTnRNR3N3SFFZRFZSME9CQllFRkJmSmFYbGlLTGVHSGVPT1ExRHJhbGZkCi9hOVVNQjhHQTFVZEl3UVlNQmFBRkJmSmFYbGlLTGVHSGVPT1ExRHJhbGZkL2E5VU1BOEdBMVVkRXdFQi93UUYKTUFNQkFmOHdHQVlEVlIwUkJCRXdENElOWTJ4MWMzUmxjaTVzYjJOaGJEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBUFhzQTlYUE1nUU1wUXJqYUtVcFBCVHZBQzhlY2wwWXE1clhUWW1VblA2cTNUQkRYSnl4ZzFKWUJOaUtPClREQ2tKRCtvVnF2bFNnb0YzYkl6cUsyZkVUQ0lpQzVzQXVCdXU2VVlhOGtOSXdHajlWMy9BblZxbWZEaGhoem4KMjJRdTVBczlJUFVienNyR0tlZk93dFJ4ZWxkenFkYlBDSVU2aFdSdi81eFhOOWh0MzhFZVdPS3Zrb2xRVHdzZgpGTlg1b0xOcjZORWhRRndJanB0aitPSVhCa244UEFEaXdzSXVhZFZyMkVMVnIrbGozTjIrcUFKdGxVbFZlMFFFCko5cTl5Yjd1QVZybU1nZks2NVJhVmRCRjF0cHVyYVVRN1F0dVVFbTBhaFlUNXRrWTRldGdZdEp5SjcvUnJHenUKSzBlVWtqN3NFaUZZOHE0YzNRcHErbnhuWXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
